"""add code embeddings

Revision ID: 999999999998
Revises: 999999999999
Create Date: 2026-09-01 12:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '999999999998'
down_revision: Union[str, None] = '999999999999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_embeddings_analysis_id'), 'code_embeddings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_code_embeddings_file_path'), 'code_embeddings', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_embeddings_id'), 'code_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_code_embeddings_repository_id'), 'code_embeddings', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_embeddings_repository_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_file_path'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_analysis_id'), table_name='code_embeddings')
    op.drop_table('code_embeddings')
    # ### end Alembic commands ###
